version: 2
jobs:
  build:
    working_directory: ~/ng-project
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test
